server:
  port: 8088

spring:
  application:
    name: coze-cloud-gateway
  config:
    import: optional:nacos:coze-cloud-gateway.yml

  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 
        namespace: 
        group: DEFAULT_GROUP
      discovery:
        server-addr: 
        namespace: 
        group: DEFAULT_GROUP
